apiVersion: apps.mononoke.local/v1alpha1
kind: SpringBootApplication
metadata:
  name: petclinic
spec:
  template:
    spec:
      containers:
      - name: application
        image: scothis/petclinic
